# Generated by Django 5.0.2 on 2024-07-19 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='date',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
