# Generated by Django 5.0.2 on 2024-07-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0002_rename_user_email_emailmessage_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='email',
            new_name='user_email',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
