# Generated by Django 5.0.2 on 2024-07-22 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0003_rename_email_emailmessage_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='user_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
