# Generated by Django 5.0.2 on 2024-07-22 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0004_rename_user_email_emailmessage_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='content',
            new_name='body',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='receive_message.emailmessage')),
            ],
        ),
    ]
