# Generated by Django 5.0.2 on 2024-07-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0005_rename_content_emailmessage_body_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
