# Generated by Django 5.0.2 on 2024-07-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0006_emailmessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='body',
        ),
    ]
