# Generated by Django 5.0.2 on 2024-07-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0007_remove_emailmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='unique_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
