# Generated by Django 5.0.2 on 2024-07-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0008_emailmessage_unique_id_alter_emailmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
