# Generated by Django 5.0.2 on 2024-07-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0009_alter_emailmessage_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
