# Generated by Django 5.0.2 on 2024-07-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0010_remove_emailmessage_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
