# Generated by Django 5.0.2 on 2024-07-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0011_alter_emailmessage_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='message_id',
        ),
    ]
