# Generated by Django 5.0.2 on 2024-07-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0012_remove_emailmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
