# Generated by Django 5.0.2 on 2024-07-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_message', '0013_alter_emailmessage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='api_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='html_body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='sender',
            field=models.CharField(db_index=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
